### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by rpodcast** [JupiterBroadcasting/CasterSoundboard#11]
I just heard about this on [lup 195](http://www.jupiterbroadcasting.com/114356/rub-a-dub-grub-lup-195/) and would really like to use this for [my podcast](https://www.r-podcast.org)!  I wasn't sure if this could be installed using a typical `make` pipeline or if there was another method?  While I'm not an expert in c++ I'd be happy to assist with the project in other ways if you would like.  On a separate note we finally have a way to execute the audio visualizer app from the command line.  See my discussion with the dev [here](https://github.com/djfun/audio-visualizer-python/issues/10)  :thumbsup:

**Comment by chasinglogic** [comment]
I'm working on a makefile and documentation for this.

**Comment by rikai** [comment]
@thercast @chasinglogic There's actually no need for a makefile, qmake [auto-generates a makefile](http://stackoverflow.com/a/1368577) when run. Qt ftw 👍

**Comment by rikai** [comment]
All that you should need to do is run `qmake` followed by `make` to compile. :)

**Comment by rikai** [comment]
README with compile/install instructions merged. 🥇
