### ISSUE TITLE
Using CasterSoundboard while recording podcast

### ISSUE THREAD

**Issue by rpodcast** [JupiterBroadcasting/CasterSoundboard#16]
I realize this question is not about `CasterSoundboard` itself but about enhancing my podcast workflow with it.  In my current workflow I'll use audacity to capture my voice and then in post-production I'll splice in my bumper music and opening/closing themes.  But I would much rather just play these clips with `CasterSoundboard` while I'm recording.  Is there a way to accomplish this all from the same computer?  Also is audacity or another program more suitable for this workflow?  From what I recall the previous version of the soundboard Chris was using came from a separate mac and it was brought in as a separate audio input source, but it sounds like that has been replaced by `CasterSoundboard` so I'm trying to replicate a similar setup for my workflow.  I'm hoping this can be accomplished without purchasing a huge hardware mixer since I have to be pretty mobile for my podcast recording.

**Comment by rikai** [comment]
Run the soundboard on the desktop you're capturing your audio on and capture the desktop audio on a second track
