### ISSUE TITLE
Gradually Editing Color Settings per Tile

### ISSUE THREAD

**Issue by MichaelTunnell** [JupiterBroadcasting/CasterSoundboard#21]
When you change the color of a tile and go to change again it doesn't remember the previous setting so you have to start over each time. It would be great if it would remember the current setting for more gradual adjustments.

**Comment by covarianttensor** [comment]
Big update the soundboard in about a day from now. I will include this as part of the update.

**Comment by covarianttensor** [comment]
Feature implemented. Closing now.
