### ISSUE TITLE
Open Sound Control support

### ISSUE THREAD

**Issue by guyfawcus** [JupiterBroadcasting/CasterSoundboard#22]
It'd be great to be able to trigger cues using OSC commands.

For the uninitiated, Open Sound Control (OSC) is sort of next-gen MIDI that runs over a network:
- https://en.wikipedia.org/wiki/Open_Sound_Control
- http://opensoundcontrol.org/

Similar software also utilises OSC:
- https://figure53.com/docs/qlab/v3/scripting/osc-dictionary-v3/

**Comment by guyfawcus** [comment]
This could also potentially be used for client/server communication which was brought up in issue #4 specifically @covarianttensor's [comment](https://github.com/JupiterBroadcasting/CasterSoundboard/issues/4#issuecomment-299274497)

**Comment by rikai** [comment]
Mmm, can you explain what you're envisioning when you ask for support for this? I'm having difficulty understanding what it might be useful for in the context of this application as we work with arbitrary audio clips rather than midi/notations, which is what this mostly seems focused on.

**Comment by covarianttensor** [comment]
I'll keep it in mind. There's gonna be a big update to the sound board in about a day. I'll focus on new features after that.

**Comment by guyfawcus** [comment]
Sorry, didn't give much context with that, was a bit of a brain dump before I forgot!

OSC is way past MIDI in it's capabilities, it can even be used in [QLC+](https://github.com/mcallegari/qlcplus) (Ahem, Noah 😜) to trigger lighting scenes.

To be honest, this is mainly because I'm currently working on a Python3 project (which I plan on uploading to GitHub within a week) that can take either user-input on the keyboard or a serial string from an Arduino or something (for physical buttons) then generates OSC messages which are read by the cueing software I use at work (QLab - I'm a sound engineer) to trigger sound-effects. This could then be used in conjunction with CasterSoundboard, press a button that's hooked up to a micro and one of the cues would play.

It could be as simple as `'/CasterSoundboard/<tab-name>/<key-sound-is-triggered-with>/<command>'`
so `'/CasterSoundboard/unfilter/h/play'` would trigger the Obama "Hey!" clip.

**Comment by covarianttensor** [comment]
Okay so I've been looking into this some more and THIS IS A MUST HAVE feature. I will add an OSC server to CasterSoundboard after I add audio ducking. Can you refer me to software/scripts I can use to generate OSC messages, so I can test against CasterSoundboard?

Update:
I think I already found I library I can use:
https://github.com/MugenSAS/osc-cpp-qt

**Comment by covarianttensor** [comment]
@maelstrom59  I'm already working on adding OSC support as I type this. The soundbaord can now receive messages or bundles.

**Comment by guyfawcus** [comment]
Good stuff! 😀 

In regards to scripts for testing, there are a few options but I usually find it easier to just do it from scratch in Python 3 using [python-osc](https://github.com/attwad/python-osc).

Install it using:
```bash
pip3 install python-osc
```

In-keeping with my example above:

```python
#!/usr/bin/env python3
from pythonosc import udp_client

client = udp_client.SimpleUDPClient('127.0.0.1', 54321)
client.send_message('/CasterSoundboard/unfilter/h', 'play')
``` 
would send the `play` command to the `h` key.

To emulate the server side (only for completeness of this example, you can obviously skip this step if you've already got one going in CasterSoundboard!):

```python
#!/usr/bin/env python3
from pythonosc import dispatcher
from pythonosc import osc_server


def do_thing(addr, val):
    print('Address:', addr)
    print('Value:', val)

    if addr == '/CasterSoundboard/unfilter/h' and val == 'play':
        print('Hey!')


dispatcher = dispatcher.Dispatcher()
dispatcher.map('/CasterSoundboard/unfilter/h', do_thing)

server = osc_server.ThreadingOSCUDPServer(('127.0.0.1', 54321), dispatcher)
server.serve_forever()
```

would print:

```
Address: /CasterSoundboard/unfilter/h
Command: play
Hey!
```

when it received a message from the first script.

**Comment by guyfawcus** [comment]
Just watched the latest JB video - [Studio Tour Quickie // VLOG 45](http://www.jupiterbroadcasting.com/114626/studio-tour-quickie-vlog-45/) and noticed the Linux powered sound desk Chris has been talking about, it's the [Behringer X32](http://www.music-group.com/Categories/Behringer/Mixers/Digital-Mixers/X32/p/P0ASF).

I'm already somewhat familiar with it as I've come across it before at work and knew about X32 Edit (the controller software) because of it's Linux compatibility but I did a [bit more research](https://media.music-group.com/media/PLM/data/docs/P0ASF/X32_M_EN.pdf) and guess what protocol the software uses to control the desk... 😜 
>Also offered is a separate remote editor running on host computers that will 
allow for complete editing control of the X32 via Ethernet. Check out behringer.
com for more information. 

>Tip: The X32 remote communication is OSC-based (open sound control) and we 
will share the protocol on our website, allowing developers to design their own 
control software. Stay tuned to behringer.com for details on the OSC protocol.

Yup, that's right, you could (implementation dependant) potentially control the desk with CasterSoundboard and vice versa! Something like, when a clip is playing, mute the Mumble room channel, or, configure a button on the desk to trigger a clip.

At the very least, you could grab the OSC bindings for your favourite programming language and control the soundboard and the desk using similar commands. *Wink wink* [JBot](https://github.com/rikai/Showbot) @rikai @ChrisLAS @dominickm 

There isn't much in the manual about the commands but the MUSIC Group wiki (which could do with some work...) has a load of information about it:
http://behringerwiki.music-group.com/index.php?title=OSC_Remote_Protocol

**Comment by covarianttensor** [comment]
I've made CasterSoundBoard print all osc direct message commands sent to it, we can find out what messages are sent that way. Right now, I have one-way OSC control working, currently working on two-way control to make things like TouchOSC work with CasterSoundboard. 

I'm not done, but would you be willing to test what I have so far @maelstrom59 ? I'll commit what I have to the development branch.
 
OSC Message Format (ONE-WAY):
`/castersoundboard/board/<board-name>/player/<player-name>/modify/<interface-name>  <value>`

Examples:
ADDRESS:
`/castersoundboard/board/No` `Name/player/,/modify/track_position`
VALUE (float):
`0.5`
ADDRESS:
`/castersoundboard/board/No` `Name/player/W/modify/volume`
VALUE (float):
`0.9`
ADDRESS:
`/castersoundboard/board/No` `Name/player/G/modify/loop_state`
VALUE (int):
`0`
ADDRESS:
`/castersoundboard/board/No` `Name/player/G/modify/loop_state`
VALUE(int):
`1`
ADDRESS:
`/castersoundboard/board/No` `Name/player/D/modify/play_state/play`
VALUE (int):
`1`
ADDRESS:
`/castersoundboard/board/No` `Name/player/D/modify/play_state/pause`
VALUE (int):
`1`
ADDRESS:
`/castersoundboard/board/No` `Name/player/D/modify/play_state/stop`
VALUE (int):
`1`

Code Example:
```python
#!/usr/bin/env python3
from pythonosc import udp_client

client = udp_client.SimpleUDPClient('127.0.0.1', 5051)
client.send_message('/castersoundboard/board/No Name/player/,/modify/track_position', 0.5)
```

I will make the port changeable, but for now it's listening on port 5051 for OSC packets. Please don't judge what I have so far, as I am not done. I am just letting you preview it so I can get feedback from you. I will most likely be done with the full implementation in about two to three days from now.

Please build from the development branch and test @maelstrom59 

Please be aware OSC commands print to the bottom status bar of Caster Soundboard and stay there for only half a second.

I will research the Behringer X32 and see how I can have it interface with CasterSoundboard.

**Comment by guyfawcus** [comment]
This is awesome! Don't worry about me judging, I'm still pretty new to lower-level languages so you could probably hide a lot without me noticing 😛

I'd love to test it out but unfortunately it's failing to compile `ColorConversion.cpp` for some reason:
<details><summary>Click to expand error test</summary>

```
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtMultimedia -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o ColorConversion.o ColorConversion.cpp
In file included from ColorConversion.cpp:1:0:
ColorConversion.h: In function ‘HSL RGBtoHSL(const RGB&)’:
ColorConversion.h:24:9: warning: variable ‘hsl’ set but not used [-Wunused-but-set-variable]
     HSL hsl;
         ^~~
ColorConversion.h:90:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
ColorConversion.h: In function ‘RGB HSLtoRGB(const HSL&)’:
ColorConversion.h:96:9: warning: variable ‘rgb’ set but not used [-Wunused-but-set-variable]
     RGB rgb;
         ^~~
ColorConversion.h:102:10: warning: unused variable ‘h’ [-Wunused-variable]
     uint h = hsl.h;
          ^
ColorConversion.h:167:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
ColorConversion.cpp: In function ‘int* getRGB_fromHLS(int, int, int)’:
ColorConversion.cpp:12:37: error: call of overloaded ‘abs(double)’ is ambiguous
     double C = (1.0 - abs(2.0*L_-1.0)) * S_;
                                     ^
In file included from /usr/include/c++/6.3.1/cstdlib:75:0,
                 from /usr/include/c++/6.3.1/stdlib.h:36,
                 from ColorConversion.h:3,
                 from ColorConversion.cpp:1:
/usr/include/stdlib.h:735:12: note: candidate: int abs(int)
 extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
            ^~~
In file included from /usr/include/c++/6.3.1/stdlib.h:36:0,
                 from ColorConversion.h:3,
                 from ColorConversion.cpp:1:
/usr/include/c++/6.3.1/cstdlib:185:3: note: candidate: __int128 std::abs(__int128)
   abs(__GLIBCXX_TYPE_INT_N_0 __x) { return __x >= 0 ? __x : -__x; }
   ^~~
/usr/include/c++/6.3.1/cstdlib:180:3: note: candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^~~
/usr/include/c++/6.3.1/cstdlib:172:3: note: candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^~~
ColorConversion.cpp:13:53: error: call of overloaded ‘abs(double)’ is ambiguous
     double X = C * (1.0 - abs(fmodf(H/60.0, 2.0)-1.0));
                                                     ^
In file included from /usr/include/c++/6.3.1/cstdlib:75:0,
                 from /usr/include/c++/6.3.1/stdlib.h:36,
                 from ColorConversion.h:3,
                 from ColorConversion.cpp:1:
/usr/include/stdlib.h:735:12: note: candidate: int abs(int)
 extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
            ^~~
In file included from /usr/include/c++/6.3.1/stdlib.h:36:0,
                 from ColorConversion.h:3,
                 from ColorConversion.cpp:1:
/usr/include/c++/6.3.1/cstdlib:185:3: note: candidate: __int128 std::abs(__int128)
   abs(__GLIBCXX_TYPE_INT_N_0 __x) { return __x >= 0 ? __x : -__x; }
   ^~~
/usr/include/c++/6.3.1/cstdlib:180:3: note: candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^~~
/usr/include/c++/6.3.1/cstdlib:172:3: note: candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^~~
Makefile:1260: recipe for target 'ColorConversion.o' failed
make: *** [ColorConversion.o] Error 1

```
</details>

Not sure why, considering it hasn't changed from the master branch. I've tried fixing it, got as far as [this wiki page](https://en.wikibooks.org/wiki/GCC_Debugging/g%2B%2B/Errors/call_of_overloaded_function_is_ambiguous) and started going down a rabbit hole. I'll keep trying to figure it out but would you mind having a look if you get the chance, I cant wait to try this!

**Comment by guyfawcus** [comment]
Got it working! Albeit via an extremely hacky method - I just deleted the lines in the generated Makefile that referenced `ColorConversion.cpp` and `ColorConversion.o` under `SOURCES` and `OBJECTS`.

Definitely something that still needs investigating by someone with more knowledge in C++ than I, but in the meantime, I've got some stuff to play around with!

**Comment by covarianttensor** [comment]
Hmm, weird, I've made no changes to that ColorConversion file.

**Comment by rikai** [comment]
I suspect this is being caused by differences in GCC versions handling things differently.

**Comment by guyfawcus** [comment]
With a file loaded into cue 1, I tried all of your examples:
```python
client.send_message('/castersoundboard/board/No Name/player/1/modify/track_position', 0.5)

client.send_message('/castersoundboard/board/No Name/player/1/modify/volume', 0.8)

client.send_message('/castersoundboard/board/No Name/player/1/modify/loop_state', 1)
client.send_message('/castersoundboard/board/No Name/player/1/modify/loop_state', 0)

client.send_message('/castersoundboard/board/No Name/player/1/modify/play_state/play', 1)
client.send_message('/castersoundboard/board/No Name/player/1/modify/play_state/pause', 1)
client.send_message('/castersoundboard/board/No Name/player/1/modify/play_state/stop', 1)
```

it's a great start for sure, I've already integrated it into the application I mentioned earlier (still planning to release it in a few days).

Just a couple of small issues though:
* `track_position` works fine but it's not always very useful. Maybe this could be renamed `track_position_percent` and `track_position` could still accept a float, but instead, it be used for the number of seconds into the track?

* `pause` and `stop` both work but `play` seems to start the track from the beginning rather than the location it was paused at. This would be fine if there was a `resume` argument or something similar.

EDIT: Formatting and resume idea

**Comment by covarianttensor** [comment]
track_position will be renamed to track_position_percent and I will add resume option to api.

**Comment by covarianttensor** [comment]
Full open sound control implemented. Will document api in wiki soon. Can control with touchOSC. Sample layout added to repo.

**Comment by guyfawcus** [comment]
Amazing! Thanks again for all your work on this 👍 I'll get cracking on the wiki as soon as I can as well.
