### ISSUE TITLE
sudo make uninstall tries to remove /bin/

### ISSUE THREAD

**Issue by tsimonq2** [JupiterBroadcasting/CasterSoundboard#23]
I was trying to run `sudo make uninstall` when I was met with this:

```
$ sudo make uninstall
rm -f /bin/CasterSoundboard
rmdir /bin/ 
rmdir: failed to remove '/bin/': Directory not empty
Makefile:463: recipe for target 'uninstall_target' failed
make: [uninstall_target] Error 1 (ignored)
```

I was just lucky this wasn't an rm -rf!

Any chance this could **not** happen? :)

**Comment by bennyprofane** [comment]
according to this [thread](http://stackoverflow.com/questions/28480849/qmake-make-uninstall-tries-to-remove-system-folders-containing-files-installed) that's a feature not a bug :^)
