### ISSUE TITLE
CasterSoundboard is now feature complete and is now in BETA

### ISSUE THREAD

**Issue by covarianttensor** [JupiterBroadcasting/CasterSoundboard#25]
I recently finished implementing a lot of basic features needed by the program. 
### New Features: ###
* Sound board profile saving!!!! (All settings per tab are saved, yay!) MAJOR FEATURE!!!!
* Touch friendly interface.
* Global audio killing
* Tab renaming
* Looping
* Sound Cues. You can now choose a start time and a stop time when playing a sound file. Looping works too!
* Track position bar
* Background color settings are now saved and set when you use the color picker dialogue box.
* Plus a few more not mentioned here...

This software is now in BETA and will require help from everyone to find bugs and make minor improvements/changes.

I'm really thankful for all the packing and README file commits. You guys are better at packing software than me, so thanks a bunch!

![screenshot from 2017-05-10 02-26-45](https://cloud.githubusercontent.com/assets/507320/25892201/77ee05e4-3528-11e7-8c67-97be0cd2dc88.png)

**Comment by guyfawcus** [comment]
Very nice! Thank you so much for this. I'm going to start using this at work wherever I can, only on the smaller non-critical shows for now but I'm hoping at some point this'll replace QLab on a lot of gigs after it matures a little. Having to bring a mac just for playing a few stings makes me sad (I feel your pain @ChrisLAS ) .

**Comment by guyfawcus** [comment]
Ah, just tried building it but now I'm getting some compiler errors when I run `make`:
```MainWindow.cpp: In member function ‘void MainWindow::saveTab()’:
MainWindow.cpp:197:28: error: ‘Qt_5_8’ is not a member of ‘QDataStream’
             out.setVersion(QDataStream::Qt_5_8);
                            ^~~~~~~~~~~
MainWindow.cpp:215:32: error: ‘Qt_5_8’ is not a member of ‘QDataStream’
                 out.setVersion(QDataStream::Qt_5_8);
                                ^~~~~~~~~~~
MainWindow.cpp: In member function ‘void MainWindow::saveAsTab()’:
MainWindow.cpp:257:28: error: ‘Qt_5_8’ is not a member of ‘QDataStream’
             out.setVersion(QDataStream::Qt_5_8);
                            ^~~~~~~~~~~
MainWindow.cpp: In member function ‘void MainWindow::openProfile()’:
MainWindow.cpp:287:23: error: ‘Qt_5_8’ is not a member of ‘QDataStream’
         in.setVersion(QDataStream::Qt_5_8);
                       ^~~~~~~~~~~
Makefile:676: recipe for target 'MainWindow.o' failed
make: *** [MainWindow.o] Error 1
```

cfe67a2cba2cea5330d623c4d37c56c5ed4db6f4 appears to have broken something when building on my Fedora 25 (Linux 4.10.9) machine. Please excuse my lack of knowledge with C++ and let me know if there is any other info I can provide.

**Comment by odysseywestra** [comment]
Just letting you know that the recent changes removed the ability to use the make commands like intended on the readme file. Which also breaks the PKGBUILD from the AUR as well.

```
[albert@Helios CasterSoundboard]$ make install
make: Nothing to be done for 'install'.
```

**Comment by covarianttensor** [comment]
I'll look into this. Please note that you this program was made with Qt 5.8. Not sure what dependencies that affects when packaging. I think I'll just make the serialize use the default compiled version to ease builds.

**Comment by covarianttensor** [comment]
Please try building again @maelstrom59 I switched from Qt_5_8 serializer to whatever the compiler default is. Should compile now.

**Comment by guyfawcus** [comment]
@covarianttensor: 👍 yup, all good. 3312dbfee5c0ca135822105b7b78bc9f31d7c03e fixed the build, thanks!
