### ISSUE TITLE
Added a Launcher File

### ISSUE THREAD

**Issue by odysseywestra** [JupiterBroadcasting/CasterSoundboard#26]
We probably should have a desktop file created so user don't have to launch it from the terminal.

**Comment by MichaelTunnell** [comment]
CasterSoundboard does not have any packages offered at the moment so there is no need for desktop files until packages are made. In the case of the AUR package, the AUR PKGBUILD should just create the desktop file in it.

If compiling yourself on another distro then GTK distros should use MenuLibre and KDE Plasma distros should use KMenuEdit to easily make desktop files for the compiled soundboard.

------
With that said, when packages are made desktop files should totally be included.

**Comment by odysseywestra** [comment]
Okay. I'm just going on my experience with gimp and MyPaint which do include desktop files by default in their repo. I believe having them available will keep the metadata consistent no matter how it is package for other distros.

Using a tool to create the launcher is a good temporary measure, but not a good permeant solution. 

So eventually like you said, once more packages are made we should have them available.

**Comment by z3ntu** [comment]
I agree that the .desktop file should be included in the repo and not be handled by the distribution packaging.

**Comment by covarianttensor** [comment]
I'll add one.

**Comment by ghost** [comment]
After dd5bb29 we can close this one.
