### ISSUE TITLE
Remote control feature

### ISSUE THREAD

**Issue by fredmayor88** [JupiterBroadcasting/CasterSoundboard#29]
Hey, are there any plans for remote control? Via a web-gui, phone app, whatever? Adding a restful API to play already defined sounds would be nice.

**Comment by guyfawcus** [comment]
In issue #22 @covarianttensor is [currently working on](https://github.com/JupiterBroadcasting/CasterSoundboard/issues/22#issuecomment-300740029) adding Open Sound Control (OSC) support which would allow you to control CasterSoundboard using any application that supports sending OSC messages, TouchOSC ([Android](https://play.google.com/store/apps/details?id=net.hexler.touchosc_a) or [IOS](https://itunes.apple.com/us/app/touchosc/id288120394)) is one such example for mobile. If you want to talk to it pragmatically, check out the [example Python 3 code](https://github.com/JupiterBroadcasting/CasterSoundboard/issues/22#issuecomment-300868212) I wrote on the issue.

As far as I'm aware, that's where the remote priorities are at the moment. Let us know if you have any particular use-cases that would require a different method of communication.

**Comment by covarianttensor** [comment]
Yeah what he said.

**Comment by covarianttensor** [comment]
To elaborate some more. Once CasterSoundboard supports two-way Open Sound Control communication, you will be able to use a program like TouchOSC on an ipad or android phone/tablet to remote control CasterSoundboard. Just be patient, will most likely be done in about three days from now.

Also, I'm hoping people in the community will create TouchOSC layouts for multiple devices to use with CasterSounboard, those layouts will be added to the repo.

**Comment by covarianttensor** [comment]
Feature implemented via open sound control. Use TouchOSC to remote the soundboard.
