### ISSUE TITLE
New Major Feature Implemented (Open Sound Control Server)

### ISSUE THREAD

**Issue by covarianttensor** [JupiterBroadcasting/CasterSoundboard#33]
New feature lets you control the soundboard by using anything capable of sending OSC messages. I recommend you use TouchOSC and run it on your tablet or phone (iOS/Android) to control the soundboard. I made a test layout and added it to the repo so you can see how it works. Please note, only one player is in the layout.

![screenshot from 2017-05-14 22-59-13](https://cloud.githubusercontent.com/assets/507320/26044409/00c75130-38f9-11e7-8def-a209d44bb9b7.png)

I'm requesting people to create layouts for as many devices as possible to be added to the repo so other people can use them.

As always, please look for bugs. I will document how to use the api in the wiki when I have time. I've been working non-stop to add this feature.

Please update your builds.

PS:
Your *.caster soundbaord profiles are not gonna work with this new build because I made major changes to the backed implementation of the soundboard players. Please create new ones. Sorry for the inconvenience.

**Comment by z3ntu** [comment]
Unrelated to this issue (and I didn't want to open a new "discussion"): 
![spectacle k17358](https://cloud.githubusercontent.com/assets/3768500/26122346/6dd98462-3a77-11e7-9a97-68f3aab2e352.png)

😜 
Unfortunately based on 3e63531 as 851bfcc (and later) will fail the compilation with the following error:

```
libs/osc/composer/OscContentComposer.cpp: In function 'void __tcf_0()':
libs/osc/composer/OscContentComposer.cpp:28:12: error: definition of static data member 'OscContentComposer::mBlank' of dllimport'd class
 QByteArray OscContentComposer::mBlank(4, 0);
            ^
libs/osc/composer/OscContentComposer.cpp: In constructor 'OscContentComposer::OscContentComposer()':
libs/osc/composer/OscContentComposer.cpp:27:8: error: definition of static data member 'OscContentComposer::mHeaderBufferSize' of dllimport'd class
 qint32 OscContentComposer::mHeaderBufferSize = 128;
        ^
make[1]: *** [Makefile.Release:2018: release/OscContentComposer.o] Error 1
make[1]: Leaving directory '/tmp/CasterSoundboard/CasterSoundboard'
make: *** [Makefile:34: release] Error 2
```

**EDIT:** Another screenshot 😄 
![spectacle h17358](https://cloud.githubusercontent.com/assets/3768500/26122740/d0ec040c-3a78-11e7-904f-7dc4df6a18c2.png)

**Comment by covarianttensor** [comment]
Oh, that's because under windows the Windows  c++ msvc don't like uninitialized static constants. being initialized outsize their class. I made some changes not in this repo to get it to compile under windows. I will probably back-port those changes to this repo. At any rate, if you want something pre-compiled for windows, you can download windows version from the project's sourceforge page here:
https://sourceforge.net/projects/castersb/?source=navbar

**Comment by covarianttensor** [comment]
By the way, are you trying to compile under Windows? I just assumed from the screenshots.

**Comment by z3ntu** [comment]
No, I was compiling it with MXE :)

**Comment by covarianttensor** [comment]
Alright, I'll back-port my alterations, give me about a day.
