### ISSUE TITLE
Import/Export ability

### ISSUE THREAD

**Issue by rikai** [JupiterBroadcasting/CasterSoundboard#4]
This will depend on #3 being solved.

It would be nice if we could export setups and be able to import them elsewhere.

The idea would be upon an export it would provide a zip file that includes the state of the buttons as well as any sound files loaded into those buttons in the zip file, making setups fully portable across machines.

**Comment by covarianttensor** [comment]
I'm currently, working on this. Will be adding this feature in a day or two. Changes will be made in my repo.

**Comment by rikai** [comment]
Would you like commit access to this repo? You're the originator of the project, so i certainly wouldn't mind giving you full access here. 👍

Relating to the issue itself, there was some discussion on how to potentially implement it in pull #10

**Comment by covarianttensor** [comment]
Seems, like you guys are gonna deviate from the way I have planned. Guess I should just work on your fork to prevent duplication of work. If you'd like to give me commit access go ahead. First thing I'll do is bring in the volume slider fix I made in my original repo. Would be nice to work with other qt developers.

**Comment by rikai** [comment]
What were you planning, out of curiosity? Definitely open to good ideas :)

**Comment by covarianttensor** [comment]
One of the original features I had planned when I first started this project was to have a companion app that ran on a phone or tablet as an extra means to play sounds. The desktop app would act as a server, maybe even over the internet. For now, I am planning on adding CUE events. So each sound clip can be made to play a sound between a set start time and stop time. This is would be useful as means to play sound clips between specific time ranges. This would mean not having to edit the sound file before use on the soundboard. If you are playing a sound file of an interview, but only need to play like 10 seconds of it somewhere in the file, it would be much nicer to CUE it in the sound board. Another feature I would like to add is the ability to add a note/comment on each sound file and have that saved as part of the soundboard profile. Notes would be useful for shows like Unfilter. I would also like to make the player tiles more touch friendly by allowing the whole tile to toggle playing and pausing. We also need a way to stop all sounds at once. The volume slider has already been made touch friendly, just need commit access to apply the change to this repo. I've got other ideas, but these are the ones I feel need to be added right now.

**Comment by rikai** [comment]
You've been added as a collaborator, which gives you commit access, iirc.

As for that list, all of those sounds like good ideas.

I think for the client/server model, something like Quassel can be used as inspiration for how to do something like that in Qt, (Implementing the protocol in pure Qt is a bad idea based on their experiences, maybe something like Google Protobuf would be better suited for something like this).

If you'd like to open issues to track any or all of those things, i don't think i'd dislike any of these features, the issues we have open now are just basically just what we considered the absolute basics to be usable in a live environment

The tile toggling is mentioned in #5, btw.

**Comment by covarianttensor** [comment]
Feature implemented. Closing now.
