### ISSUE TITLE
Improved touch support

### ISSUE THREAD

**Issue by rikai** [JupiterBroadcasting/CasterSoundboard#5]
Rather than having play buttons on each tile, it would be nice if the square itself could be a play/pause button, with the volume slider being larger (easier to grab and change when using a touchscreen)

**Comment by covarianttensor** [comment]
I've already implemented this change in my original repo.

**Comment by covarianttensor** [comment]
Volumes sliders are now bigger in order to make them touch friendly. Changes committed to development and master branches.

**Comment by rikai** [comment]
The "Allow to select files using a file dialogue instead of drag & drop." from #10 is already causing issues when used with touch, so we might want to look at reverting that commit or relegating it to a subsection, rather than being triggerd on the whole button. Might be able to reuse the bit of code to make it play instead of opening a file dialog, though!

**Comment by covarianttensor** [comment]
I wasn't the one who made that change. It's gonna have to be removed. We already agreed to make the player as a whole toggle playing and pausing. We'll have to be more careful about which pull requests we accept. I'll be proposing a finalized interface/functionality very soon so everyone can be on the same page. It will include a mockup of the proposed UI.

**Comment by rikai** [comment]
Yeah, I had approved it. I misunderstood the problem and thought there has been a button added, not the entire panel. I wasn't implying you'd added it, just making you aware of things. :)

**Comment by covarianttensor** [comment]
Implemented. Closing now.
