### ISSUE TITLE
AUR entry no longer found

### ISSUE THREAD

**Issue by hexdsl** [JupiterBroadcasting/CasterSoundboard#66]
#### Description of the Problem or Feature Request
https://aur.archlinux.org/packages/castersoundboard-git is now not found (404 error) and there are no alternate entied in the AUR. Currently snapd is having some issues on many antergos/manjaro systems do the AUR was my only options for easy install. 

#### Basic system details

CasterSoundboard version+commit: AUR
Operating system: Antergos
Desktop environment: KDE

#### Steps to reproduce

1. click on https://aur.archlinux.org/packages/castersoundboard-git

**Comment by odysseywestra** [comment]
Thank you for pointing that out. I'll try to get an AUR package setup today.

**Comment by odysseywestra** [comment]
Found the AUR package from the Archive.org's wayback machine: https://web.archive.org/web/20171015234143/https://aur.archlinux.org/packages/castersoundboard-git

I was able to clone the PKGBUILD repo so it's technically still there, but for some reason not listed on the AUR. I'll see about contacting someone to see if they can re-enable the aur entry.

**Comment by odysseywestra** [comment]
@j605 Since you were the one who maintained the package according to the PKGBUILD, could you shed any light on this issue?

Related Closed issue:
https://github.com/JupiterBroadcasting/CasterSoundboard/issues/18

**Comment by covarianttensor** [comment]
Hmm, wonder if the AUR removes packages after a while? I recall this happened before with the original version about 4 years ago.

**Comment by j605** [comment]
I had orphaned the package since I don't use it and Chris and Rikai were themselves using the snap. It was cleaned up by TU as it had no votes. If someone wants to continue maintaining the package they can just push to the repo after cloning the package to become the new maininter. Sorry for the confusion!

**Comment by rikai** [comment]
I actually am using it from the aur package personally, just not in the studio :P

**Comment by GloriousEggroll** [comment]
Heads up on this - you can still clone the AUR package via:
git clone https://aur.archlinux.org/castersoundboard-git

even though the website gives 404. The PKGBUILD is missing some dependencies. it only lists qt5-multimedia, but you also need:
gstreamer gst-plugins-good gst-plugins-bad gst-plugins-ugly

**Comment by odysseywestra** [comment]
@j605 Okay I'll take over the maintenance of the AUR package. I'll also add the dependencies that @GloriousEggroll  mentioned.

**Comment by odysseywestra** [comment]
@j605 Is there a way you can transfer maintenance to me? Or do I need to go another route?

**Comment by GloriousEggroll** [comment]
@odysseywestra from post earlier in this convo:

"If someone wants to continue maintaining the package they can just push to the repo after cloning the package to become the new maininter. Sorry for the confusion!"

**Comment by odysseywestra** [comment]
Can't do that. I even changed the url to the ssh link and still can't push or pull to it.

**Comment by odysseywestra** [comment]
I probably need to be granted permission from the main maintainer of the package. That how it was when I started maintaining the mypaint-git and libmypaint-git packages.

**Comment by j605** [comment]
I can try becoming the maintainer and then granting permission to you.

**Comment by j605** [comment]
I took over the package again and if someone wants to maintain I can orphan it at that point. If I orphan it again now someone might delete the package again.

**Comment by odysseywestra** [comment]
If you want you can add me as a co-maintainer. My username on the aur is the same one here on GitHub.

**Comment by j605** [comment]
It is done :)

**Comment by odysseywestra** [comment]
Okay I was able to add myself as a maintainer on the PKGBUILD. Also I have it installed. We can consider this closed then.

**Comment by hexdsl** [comment]
thank you for resolving this.

**Comment by j605** [comment]
Regarding adding gst dependencies, this project depends only directly on qt5-multimedia so this seems adequate and namcap doesn't complain as well :)

**Comment by GloriousEggroll** [comment]
I had qt5-multimedia installed, and it did not work until I installed the additional dependencies I mentioned. The program will launch, but you cannot load any wav/mp3/aac files. You need the additional dependencies for those.

**Comment by j605** [comment]
I updated it now.
