### ISSUE TITLE
App-wide audio ducking

### ISSUE THREAD

**Issue by rikai** [JupiterBroadcasting/CasterSoundboard#7]
Would be nice to globally duck the audio with a single button

**Comment by covarianttensor** [comment]
Will add this as well, it's lower on my priority list.

**Comment by covarianttensor** [comment]
Already, Implemented in development branch. Feature will come to master branch once Open Sound Control support is fully implemented.

**Comment by covarianttensor** [comment]
Feature implemented. Now in master branch. Can be triggered with shift key
