### ISSUE TITLE
Copr repo for Fedora does not exist anymore

### ISSUE THREAD

**Issue by gbraad** [JupiterBroadcasting/CasterSoundboard#71]
The mentioned copr repository for Fedora does not exist anymore. The user has no projects under his name, so likely decided to stop supporting these, or has moved them to another namespace?

**Comment by covarianttensor** [comment]
> The mentioned copr repository for Fedora does not exist anymore. The user has no projects under his name, so likely decided to stop supporting these, or has moved them to another namespace?

Who ever was maintaining that Fedora package must of have lost interest. I don't run Fedora so I don't have any interest in maintaining that. If you would like to do that, I would happily accept a PR to your new copr package.

**Comment by covarianttensor** [comment]
I'm am currently working on version 2 of this software, so I am not in a position to maintain packages myself for various platforms. Compound that with the fact that I am working on a Roku app for Jupiter 
 Broadcasting and I end up in my current situation where I don't have much spare time for that sort of thing. Any help on that end is greatly appreciated, but don't feel obligated.

**Comment by gbraad** [comment]
I am merely remarking the need to update the README for this. I have
since worked on my own solution that works for me and does not get
affected by 'platform limitations or distribution problems'.

However, if you are serious in trying to get it to work accross
distributions, perhaps have a look at putting it out as a Flatpak
application as there is a Qt runtime AFAIK.

Note: I know there is a snap, but 'flatpak' seems to be the de facto
approach for people on Gnome and some other distros, besides
the Ubunto-derived ones.

**Comment by covarianttensor** [comment]
> I am merely remarking the need to update the README for this. I have since worked on my own solution that works for me and does not get affected by 'platform limitations or distribution problems'. However, if you are serious in trying to get it to work accross distributions, perhaps have a look at putting it out as a Flatpak application as there is a Qt runtime AFAIK.

Actually, I've been thinking of using Flatpak as well. I'll look into it.

**Comment by gbraad** [comment]
If you need help, drop a question on their mailinglist. They are very
helpful and likely can assist in getting this done and perhaps even publish
on flathub (the download repository).
