### ISSUE TITLE
Incorrect license in Snap store

### ISSUE THREAD

**Issue by volt4ire** [JupiterBroadcasting/CasterSoundboard#73]
CasterSoundboard's [license on Github](https://github.com/JupiterBroadcasting/CasterSoundboard/blob/master/LICENSE) says it's licensed under the LGPL but it's labeled as proprietary [on snapcraft.io](https://snapcraft.io/castersoundboard).
![Screenshot_20190828_075505](https://user-images.githubusercontent.com/8772017/63853878-cbd51800-c969-11e9-8cc4-0e2630e3eecb.png)

**Comment by covarianttensor** [comment]
I don't maintain the snap and the guy who set it up (rikai) is M.I.A. I'm not sure I can do anything about it.

**Comment by volt4ire** [comment]
@covarianttensor got it thanks!

**Comment by rikai** [comment]
I'm actually around, and will be happy to update it when I've got some free time, perhaps on Monday.

**Comment by covarianttensor** [comment]
OMG you're alive! Also thanks!

**Comment by rikai** [comment]
Got this updated, sorry it took so long, was in the middle of a move! :)

**Comment by volt4ire** [comment]
@rikai Thank you so much --- I hope you had a great move!
