### ISSUE TITLE
Cues not saved

### ISSUE THREAD

**Issue by tjabaut** [JupiterBroadcasting/CasterSoundboard#74]
[⚠ Please read our [contributors](CONTRIBUTING.md) document before posting]

#### Basic system details

CasterSoundboard version+commit: v1.0 BETA
Operating system: Debian 9 & 10
Desktop environment: gnome

#### Steps to reproduce

1. Add audio track
2. Set cue point to say trim initial 10 seconds
3. Save Tab
4. Close app
5. Open app and reopen saved Tab

All previous cue points are missing

**Comment by covarianttensor** [comment]
@tjabaut Please confirm latest commit fixes bug.
