### ISSUE TITLE
idea: Use filesystem as config

### ISSUE THREAD

**Issue by gabdub** [JupiterBroadcasting/CasterSoundboard#8]
Sound files could be arranged in folders as follow:
sound_root/show-name/tab-name/button-name

After choosing a show from the list (folders of sound_root), all tabs (folders under show-name) are loaded in alphabetical order. Each tab is loaded with it's buttons (files inside tab folder).

Optional: If a name starts with a number plus "_" that number is not shown.

p.e: show=LAS, tab=RMS, buttons=this is neg, get out
~/.caster/LAS/RMS/1_this is neg
~/.caster/LAS/RMS/2_get out

That way you can export/import/arrange/save all tabs and buttons using just the file browser.

Just my two cents
LASpotato ;)

**Comment by rikai** [comment]
I'm actually not a huge fan of a file-driven configuration. It feels more fragile and less flexible and doesn't really offer any advantages.

If we're building this up from scratch, i'd like to make this thing as flexible as it can be and adding arbitrary constraints when things could be easily defined in a configuration file seems like a step down the wrong path.

**Comment by gabdub** [comment]
>doesn't really offer any advantages.

You can implement this in just a couple of hours (read some files/folders + no need to graphical edit anything) and get export/import/arrange/save all tabs and button for free.
It's your baby, do as you wish.
Best wishes,
Gabriel
